## 00 - Pytorch Fundamentals:

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/python-deep-learning/discussions

In [1]:
import torch
print(torch.__version__)

2.9.1+cu128


In [2]:
print(f'CUDA Available: {torch.cuda.is_available()}')
print(f'CUDA Version: {torch.version.cuda}')

CUDA Available: True
CUDA Version: 12.8


In [3]:
!nvidia-smi

Tue Jan 13 10:29:20 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 573.22                 Driver Version: 573.22         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   58C    P8              5W /   35W |     804MiB /   4096MiB |     18%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Introduction To Tensors:

### Creating Tensors:

PyTorch tensors are created using `torch.Tensor()` - https://pytorch.org/docs/stable/tensors.html

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors:

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

``Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers``

Torch random tensors - https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [19]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1341, 0.3909, 0.5835, 0.2596],
        [0.4598, 0.0911, 0.1718, 0.9493],
        [0.5331, 0.7959, 0.8852, 0.2787]])

In [20]:
# Create a random temsor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 244, 3)) # Height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 244, 3]), 3)

### Zeros And Ones:

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensore of all ones
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
random_tensor.dtype

torch.float32

### Creating A Range Of Tensors And Tensors-Like:

In [25]:
# Use torch.range() and get deprecated message
torch.range(0, 10) # torch.range() is depricated and could be removed later. Please use torch.arange() instead, and increase the intended stop value by 1 due to an end-behavior change

C:\Users\Jake\AppData\Local\Temp\ipykernel_23836\986541486.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10) # torch.range() is depricated and could be removed later. Please use torch.arange() instead, and increase the intended stop value by 1 due to an end-behavior change


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
# Use torch.arange()
torch.arange(0, 11)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Use torch.arange()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
torch.arange(start = 0, end = 1000, step = 77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [29]:
# Create tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes:

**Note:** Tensor datatypes are one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=IN%20%computer%20%science%2C%20the%precision,used%20%to%20express%20a%20value.

In [30]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # What datatype is the tensor (e.g. float32 or float16)
                               device = None, # What device is your tensor on
                               requires_grad = False) # Whether or not to track gradients with this tensor's operations
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [34]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [35]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting Information From Tensors (Tensor Attributes):

1. Tensors not right datatype - To get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - To get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - To get device from a tensor, can use `tensor.device`

In [36]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6147, 0.1541, 0.3333, 0.0972],
        [0.6910, 0.6081, 0.8980, 0.3282],
        [0.6406, 0.1991, 0.6094, 0.8975]])

In [37]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.6147, 0.1541, 0.3333, 0.0972],
        [0.6910, 0.6081, 0.8980, 0.3282],
        [0.6406, 0.1991, 0.6094, 0.8975]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (Tensor Operations):

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [38]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [39]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [40]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [41]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [42]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication:

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [43]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [44]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [45]:
tensor @ tensor

tensor(14)

In [46]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [47]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 31.2 ms
Wall time: 1 ms


In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [49]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [50]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.6092, 0.6698],
        [1.1418, 0.6394]])

In [51]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.3170, 0.2520, 0.2528],
        [0.2494, 0.1780, 0.1676],
        [0.3649, 0.2201, 0.1826]])

In [52]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 3))

tensor([[1.2685, 2.3998, 2.7667],
        [0.9339, 2.3011, 2.5688],
        [1.8660, 2.3322, 3.0574]])

In [53]:
torch.matmul(torch.rand(10, 10), torch.rand(10, 10))

tensor([[2.4656, 4.1102, 2.5744, 2.9290, 2.6724, 2.2738, 3.0331, 2.8217, 2.7535,
         2.6858],
        [3.4079, 4.5730, 2.8558, 2.9876, 3.0305, 2.5045, 3.1188, 3.0796, 3.2907,
         3.0555],
        [2.3313, 3.0179, 2.3320, 2.4415, 2.0772, 1.6618, 2.4457, 2.2936, 2.2337,
         2.2575],
        [2.0188, 3.2067, 2.2060, 2.2155, 1.7110, 1.6655, 2.6773, 1.9919, 2.1537,
         2.3585],
        [2.5895, 3.9087, 2.6842, 3.0514, 3.0218, 2.0839, 3.6153, 2.6705, 2.4696,
         2.8352],
        [3.3479, 3.5107, 3.2104, 3.0004, 3.0376, 1.9425, 2.9322, 2.8976, 2.9086,
         2.7278],
        [2.7629, 3.7484, 3.0756, 2.8103, 2.5867, 1.7383, 3.3525, 2.9488, 2.1721,
         2.9594],
        [3.2325, 4.5084, 2.9514, 2.9822, 3.1554, 2.2498, 3.2502, 3.1108, 3.6945,
         2.9925],
        [2.4307, 3.1734, 2.3069, 2.7646, 2.5872, 1.8891, 2.4774, 2.6845, 1.8657,
         2.2328],
        [2.9584, 3.2998, 2.9032, 3.1493, 2.8075, 1.8684, 2.7168, 2.7465, 3.2245,
         2.4100]])

### One Of The Most Common Errors In Deep Learning - Shape Errors:

In [54]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [55]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [56]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [57]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [58]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [59]:
# The matrix multiplication operation works when tensor_B is transposed
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match')
print('Output:\n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding The Min, Max, Mean, Sum, Etc. (Tensor Aggregation):

In [60]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [61]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [62]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [63]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [64]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding The Positional Min And Max:

In [65]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [66]:
# Find the position in tensor that has the minimum value with argmin -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [67]:
x[0]

tensor(1)

In [68]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [69]:
x[9]

tensor(91)

## Reshaping, Stacking, Squeezing, And Unsqueezing Tensors:

* Reshaping - Reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a certain shape, but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Removes all `1` dimensions from a tensor
* Unsqueeze - Add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [84]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [85]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [86]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [87]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [88]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [89]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [90]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 2)
x_stacked

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [95]:
# torch.squeeze() - Removes all single dimensions from a target tensor
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [96]:
# torch.unsqueeze() - Adds a single dimension to a target tensor at a specific dim (dimension)
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - Rearranged the dimensions of a target tensor in a specified order
x_original = torch.rand(size = (224, 244, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # Shifts axis 0 -> 1, 1 -> 2, 2 -> 0
print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}') # [color_channels, height, width]

torch.Size([1, 9])

## Indexing (Selecting Data From Tensors):

Indexing with PyTorch is similar to indexing with NumPy.

In [97]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [98]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [99]:
# Let's index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [100]:
x[0, 0]

tensor([1, 2, 3])

In [101]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [102]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [103]:
# Get all values of 0th and 1st dimensions, but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0th dimension, but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [105]:
# Get index 0 of the 0th and 1st dimension, and all values of the 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [106]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch Tensors & NuPy:

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor to NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # Warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64, unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [110]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [111]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [112]:
numpy_tensor.dtype

dtype('float32')

In [113]:
# Change the tensor, what happens to `numpy_tensor`
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (Trying To Take The 'Random' Out Of Random):

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavor" the randomness.

In [118]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2638, 0.0463, 0.6227, 0.7043],
        [0.6961, 0.2602, 0.7059, 0.1095],
        [0.1555, 0.7593, 0.5353, 0.1815]])
tensor([[0.8021, 0.9507, 0.0839, 0.3073],
        [0.1157, 0.6264, 0.2330, 0.6073],
        [0.4051, 0.6733, 0.1832, 0.3354]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [120]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running Tensors And PyTorch Objects On The GPUs (And Making Faster Computations)

GPUs = Faster computation on numbers; thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting A GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well).
2. Use your own GPU - Takes a libble bit of setup and requires the investment of purchasing a GPU, there's lots of options..., see this post for what option to get: https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2 and 3, PyTorch + GPU drovers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [121]:
!nvidia-smi

Wed Jan 14 11:52:53 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 573.22                 Driver Version: 573.22         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   57C    P8              5W /   35W |     890MiB /   4096MiB |     17%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check For GPU Access With PyTorch

In [122]:
# Check For GPU Access With PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch, since it's capable of running compute on the GPU or CPU, it's best practice to set up device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if availabe, else default to CPU

In [123]:
# Set up device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [124]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting Tensors (And Models) On The GPU:

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [126]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device = 'cpu')

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [127]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving Tensors Back To The CPU:

In [128]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [129]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises & Extra-Curriculum:

See exercises for this notebook here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises